import type { FieldModifier, FieldType, ParsedField, ParsedSchema } from "../types/schema-types";

function mapFieldType(fieldType: FieldType): string {
  if (fieldType === "String") {
    return "string";
  }

  if (fieldType === "Int") {
    return "number";
  }

  if (fieldType === "Boolean") {
    return "boolean";
  }

  return "Date";
}

function hasModifier(field: ParsedField, modifierType: FieldModifier["type"]): boolean {
  return field.modifiers.some((modifier) => modifier.type === modifierType);
}

function hasAutoincrementDefault(field: ParsedField): boolean {
  return field.modifiers.some(
    (modifier) => modifier.type === "default" && modifier.value === "autoincrement()",
  );
}

function generateInterfaceBlock(modelName: string, fields: ParsedField[]): string {
  const lines = fields.map((field) => {
    const optionalMarker = hasModifier(field, "optional") ? "?" : "";
    return `  ${field.name}${optionalMarker}: ${mapFieldType(field.type)};`;
  });

  return [`export interface ${modelName} {`, ...lines, `}`].join("\n");
}

function generateCreateInputBlock(modelName: string, fields: ParsedField[]): string {
  const lines = fields
    .filter((field) => !(hasModifier(field, "id") && hasAutoincrementDefault(field)))
    .map((field) => {
      const optionalMarker =
        hasModifier(field, "optional") || hasModifier(field, "default") ? "?" : "";
      return `  ${field.name}${optionalMarker}: ${mapFieldType(field.type)};`;
    });

  return [`export type Create${modelName}Input = {`, ...lines, `}`].join("\n");
}

export function generateTypes(schema: ParsedSchema): string {
  const blocks: string[] = ["// Generated by ScratchORM - do not edit manually"];

  for (const model of schema.models) {
    blocks.push(generateInterfaceBlock(model.name, model.fields));
    blocks.push(generateCreateInputBlock(model.name, model.fields));
  }

  return `${blocks.join("\n\n")}\n`;
}
